### ISSUE TITLE
solc.js missing from downloaders directory

### ISSUE THREAD

**Issue by YazzyYaz** [ETCDEVTeam/emerald#11]
When I run `npm install -g https://github.com/ETCDEVTeam/emerald.git`, I get an error at the end where it's complaining about missing the `solc.js` file from the `downloaders` directory.

```
✔ sputnikvm-dev: finished installation
✔ emerald-wallet: finished installation
✔ emerald-explorer: finished installation
module.js:549
    throw err;
    ^

Error: Cannot find module '/Users/yazkhoury/.nodenv/versions/8.11.1/lib/node_modules/emerald/downloaders/solc.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
```

Looking inside the `downloaders` directory indeeds shows `solc.js` is missing even though it's being referenced here in this file: https://github.com/ETCDEVTeam/emerald/blob/master/package.json#L9

**Comment by YazzyYaz** [comment]
@shanejonas thank you for fixing 👍
